[package]
name = "chihiro"
version = "0.1.0"
authors = ["Julius de Bruijn <bruijn@prisma.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.0-alpha.6"
futures-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
hyper-tls = "0.4.0-alpha.4"
base64 = "0.11"
structopt = "0.3"
indicatif = "0.13"
metrics-runtime = "0.12"
metrics-core = "0.5"
metrics = "0.12"
serde = "1"
serde_json = "1"
http = "0.1"
elastic = "~0.21.0-pre.5"
toml = "0.5"
hdrhistogram = "6.3"
walkdir = "2"
console = "0.9"
rand = "0.7"
chrono = "0.4"
