identifier = "SQL Load Test Prisma Query Engine (typescript + rust)"
duration_per_test = 60 # seconds
elastic_endpoint = "https://16a31d8b2f8042df82b75bd7759edb00.eu-central-1.aws.cloud.es.io:9243/"

[rates]
very_slow = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
slow = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
medium = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
fast = [20, 40, 60, 80, 100, 120, 140, 160, 180, 200]
very_fast = [50, 100, 150, 200, 250, 300, 350, 400, 450, 500]

[[test_run]]
path = "./queries/sql_load_test/photon"
[test_run.variables.user_id]
minimum = 1
maximum = 3000000
[test_run.variables.comment_id]
minimum = 1
maximum = 30000000
[test_run.variables.post_id]
minimum = 1
maximum = 30000000
[test_run.variables.like_id]
minimum = 1
maximum = 150000000
