identifier = "master_test_run"
duration_per_test = 5 # seconds

[[test_run]]
path = "./queries/"
[test_run.variables.artist_id]
minimum = 1
maximum = 275
[test_run.variables.track_id]
minimum = 1
maximum = 3503
