version: "3"
services:
  mysql:
    image: mysql:5.7
    command: mysqld
    restart: always
    volumes:
      - ./chinook/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: prisma
    ports:
      - "3306:3306"
    tmpfs: /var/lib/mysql
volumes:
  postgres:
